#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Application;
use Symfony\Component\Console\Command\AnalyticCommand;
ini_set('memory_limit','2048M');
error_reporting(E_ALL & ~E_NOTICE);
$application = New Application('China unicom tool', '1.0.0');
$defaultCommand = new AnalyticCommand();
$application->add($defaultCommand);
$application->setDefaultCommand($defaultCommand->getName());
$application->setVersion('1.0.0');

$application->run();
